/**
 * @name TableColumnsInfo
 * @description 테이블 컬럼 정보
 */
const TableColumnsInfo = {
  DATACENTERS: [
    { header: '', accessor: 'iconStatus', clickable: false }, 
    { header: '이름', accessor: 'name', clickable: true }, 
    { header: '코멘트', accessor: 'comment', clickable: false },
    { header: '스토리지 유형', accessor: 'storageType', clickable: false },
    { header: '상태', accessor: 'status', clickable: false },
    { header: '호환 버전', accessor: 'compatVersion', clickable: false },
    { header: '설명', accessor: 'description', clickable: false },
  ],
  CLUSTERS_FROM_DATACENTER: [
    { header: '이름', accessor: 'clusterName' },
    { header: '호환 버전', accessor: 'version' },  // 호환 버전 열 추가
    { header: '설명', accessor: 'description' }
  ],
  STORAGE_DOMAIN_FROM_DATACENTER: [
    { header: '', accessor: 'icon', clickable: false, style: { textAlign: 'center' } },
    { header: '이름', accessor: 'name', clickable: false },
    { header: '데이터 센터 내의 도메인 상태', accessor: 'domainStatus', clickable: false },
  ],
  QOSS_FROM_DATACENTER: [
    { header: '이름', accessor: 'QosName' },
    { header: '호환 버전', accessor: 'version' },
    { header: '설명', accessor: 'description' }
  ],
  NETWORKS: [
    { header: '이름',       accessor: 'name',          clickable: true },
    { header: '설명',       accessor: 'description',    clickable: false },
    { header: '데이터센터',  accessor: 'dataCenter',     clickable: false },
    { header: '공급자',     accessor: 'provider',       clickable: false },
    { header: '포트분리',   accessor: 'portSeparation', clickable: false },
  ],
  NETWORKS_FROM_HOST: [
    { header: '', accessor: 'icon' },
    { header: '관리되지 않음', accessor: 'unmanaged' },
    { header: 'VLAN', accessor: 'vlan' },
    { header: '네트워크 이름', accessor: 'networkName', clickable: true },
    { header: 'IPv4 주소', accessor: 'ipv4' },
    { header: 'IPv6 주소', accessor: 'ipv6' }
  ],
  LUNS: [
    { header: '', accessor: 'icon', clickable: false },
    { header: '사용자', accessor: 'user', clickable: true },
    { header: '인증 공급자', accessor: 'authProvider', clickable: false },
    { header: '네임스페이스', accessor: 'namespace', clickable: false },
    { header: '역할', accessor: 'role', clickable: false },
    { header: '생성일', accessor: 'createdDate', clickable: false },
    { header: 'Inherited From', accessor: 'inheritedFrom', clickable: false },
  ],
  LUN_SIMPLE: [
    { header: '이름', accessor: 'logicalName' },
    { header: '설명', accessor: 'description' },
  ],
  STORAGE_DOMAINS: [
    { header: '상태', accessor: 'status' },
    { header: '', accessor: 'icon' },
    { header: '도메인 이름', accessor: 'domainName' },
    { header: '코멘트', accessor: 'comment' },
    { header: '도메인 유형', accessor: 'domainType' },
    { header: '스토리지 유형', accessor: 'storageType' },
    { header: '포맷', accessor: 'format' },
    { header: '데이터 센터간 상태', accessor: 'dataCenterStatus' },
    { header: '전체 공간(GB)', accessor: 'totalSpace' },
    { header: '여유 공간(GB)', accessor: 'freeSpace' },
    { header: '확보된 여유 공간(GB)', accessor: 'reservedSpace' },
    { header: '설명', accessor: 'description' },
  ],
  STORAGES_FROM_DATACENTER: [
    { header: '', accessor: 'icon' }, // 이모티콘을 표시할 열
    { header: '', accessor: 'icon2' }, // 이모티콘을 표시할 열
    { header: '도메인 이름', accessor: 'domainName' },
    { header: '도메인 유형', accessor: 'domainType' },
    { header: '상태', accessor: 'status' },
    { header: '여유 공간 (GiB)', accessor: 'freeSpace' },
    { header: '사용된 공간', accessor: 'usedSpace' },
    { header: '전체 공간 (GiB)', accessor: 'totalSpace' },
    { header: '설명', accessor: 'description' },
  ],
  STORAGES_FROM_DISK: [
    { header: '', accessor: 'icon1', clickable: false },
    { header: '', accessor: 'icon2', clickable: false },
    { header: '도메인 이름', accessor: 'domainName', clickable: false },
    { header: '도메인 유형', accessor: 'domainType', clickable: false },
    { header: '상태', accessor: 'status', clickable: false },
    { header: '여유 공간 (GiB)', accessor: 'freeSpace', clickable: false },
    { header: '사용된 공간 (GiB)', accessor: 'usedSpace', clickable: false },
    { header: '전체 공간 (GiB)', accessor: 'totalSpace', clickable: false },
    { header: '설명', accessor: 'description', clickable: false },
  ],
  STORAGES:  [
    { header: '별칭', accessor: 'alias', clickable: true },
    { header: 'ID', accessor: 'id', clickable: false },
    { header: '', accessor: 'icon1', clickable: false },
    { header: '', accessor: 'icon2', clickable: false },
    { header: '연결 대상', accessor: 'connectionTarget', clickable: false },
    { header: '스토리지 도메인', accessor: 'storageDomain', clickable: false },
    { header: '가상 크기', accessor: 'virtualSize', clickable: false },
    { header: '상태', accessor: 'status', clickable: false },
    { header: '유형', accessor: 'type', clickable: false },
    { header: '설명', accessor: 'description', clickable: false },
  ],
  VOLUMES_FROM_HOST: [
    { header: '이름', accessor: 'name', clickable: false },
    { header: '기능', accessor: 'function', clickable: false },
    { header: '벤더', accessor: 'vendor', clickable: false },
    { header: '제품', accessor: 'product', clickable: false },
    { header: '드라이버', accessor: 'driver', clickable: false },
    { header: '현재 사용중', accessor: 'currentlyUsed', clickable: false },
    { header: '가상 머신에 연결됨', accessor: 'connectedToVM', clickable: false },
    { header: 'IOMMU 그룹', accessor: 'iommuGroup', clickable: false },
    { header: 'Mdev 유형', accessor: 'mdevType', clickable: false },
  ],
  VOLUMES_FROM_CLUSTER: [
    { header: '별칭', accessor: 'alias', clickable: false },
    { header: <i className="fa fa-chevron-left"></i>, accessor: 'icon1', clickable: false },
    { header: <i className="fa fa-chevron-left"></i>, accessor: 'icon2', clickable: false },
    { header: '가상 크기', accessor: 'virtualSize', clickable: false },
    { header: '실제 크기', accessor: 'actualSize', clickable: false },
    { header: '할당 정책', accessor: 'allocationPolicy', clickable: false },
    { header: '스토리지 도메인', accessor: 'storageDomain', clickable: false },
    { header: '생성 일자', accessor: 'creationDate', clickable: false },
    { header: '최근 업데이트', accessor: 'lastUpdate', clickable: false },
    { header: '', accessor: 'icon3', clickable: false },
    { header: '연결 대상', accessor: 'connectionTarget', clickable: false },
    { header: '상태', accessor: 'status', clickable: false },
    { header: '유형', accessor: 'type', clickable: false },
    { header: '설명', accessor: 'description', clickable: false },
  ],
  VNIC_PROFILES: [
    { header: '이름', accessor: 'name', clickable: false },
    { header: '네트워크', accessor: 'network', clickable: false },
    { header: '데이터 센터', accessor: 'dataCenter', clickable: false },
    { header: '호환 버전', accessor: 'compatVersion', clickable: false },
    { header: 'QoS 이름', accessor: 'qosName', clickable: false },
    { header: '네트워크 필터', accessor: 'networkFilter', clickable: false },
    { header: '포트 미러링', accessor: 'portMirroring', clickable: false },
    { header: '통과', accessor: 'passthrough', clickable: false },
    { header: '설명', accessor: 'description', clickable: false },
  ],
  CLUSTERS_1: [
    { header: '상태', accessor: 'status', clickable: false },
    { header: '이름', accessor: 'name', clickable: true },
    { header: '코멘트', accessor: 'comment', clickable: false },
    { header: '호환 버전', accessor: 'version', clickable: false },
    { header: '설명', accessor: 'description', clickable: false },
    { header: '클러스터 CPU 유형', accessor: 'cpuType', clickable: false },
    { header: '호스트 수', accessor: 'hostCount', clickable: false },
    { header: '가상 머신 수', accessor: 'vmCount', clickable: false },
    { header: '업그레이드 상태', accessor: 'upgradeStatus', clickable: false },
  ],
  CLUSTERS: [
    { header: '이름', accessor: 'name', clickable: false },
    { header: '호환 버전', accessor: 'compatVersion', clickable: false },
    { header: '연결된 네트워크', accessor: 'connectedNetwork', clickable: false },
    { header: '네트워크 상태', accessor: 'networkStatus', clickable: false },
    { header: '필수 네트워크', accessor: 'requiredNetwork', clickable: false },
    { header: '네트워크 역할', accessor: 'networkRole', clickable: false, style: { textAlign: 'center' } },
    { header: '설명', accessor: 'description', clickable: false },
  ],
  CLUSTERS_POPUP: [
    { header: '이름', accessor: 'name', clickable: false },
    { header: '모두 할당', accessor: 'allAssigned', clickable: false },
    { header: '모두 필요', accessor: 'allRequired', clickable: false },
    { header: '가상 머신 네트 관리', accessor: 'vmNetMgmt', clickable: false, style: { textAlign: 'center' } },
    { header: '네트워크 출력', accessor: 'networkOutput', clickable: false },
    { header: '마이그레이션 네트워크', accessor: 'migrationNetwork', clickable: false },
    { header: 'Gluster 네트워크', accessor: 'glusterNetwork', clickable: false },
    { header: '기본 라우팅', accessor: 'defaultRouting', clickable: false },
  ],
  HOSTS: [
    { header: '', accessor: 'icon', clickable: false },
    { header: '이름', accessor: 'name', clickable: false },
    { header: '클러스터', accessor: 'cluster', clickable: false },
    { header: '데이터 센터', accessor: 'dataCenter', clickable: false },
    { header: '네트워크 장치 상태', accessor: 'networkDeviceStatus', clickable: false },
    { header: '비동기', accessor: 'async', clickable: false },
    { header: '네트워크 장치', accessor: 'networkDevice', clickable: false },
    { header: '속도', accessor: 'speed', clickable: false },
    { header: 'Rx', accessor: 'rx', clickable: false },
    { header: 'Tx', accessor: 'tx', clickable: false },
    { header: '총 Rx', accessor: 'totalRx', clickable: false },
    { header: '총 Tx', accessor: 'totalTx', clickable: false },
  ],
  HOSTS_ALT: [
    { header: '', accessor: 'iconStatus', clickable: false },
    { header: '', accessor: 'iconWarning', clickable: false },
    { header: '', accessor: 'iconSPM', clickable: false },
    { header: '이름', accessor: 'name', clickable: true },
    { header: '코멘트', accessor: 'comment', clickable: false },
    { header: '호스트 이름/IP', accessor: 'hostname', clickable: false },
    { header: '클러스터', accessor: 'cluster', clickable: true }, // 클러스터 컬럼에 clickable 추가
    { header: '데이터 센터', accessor: 'dataCenter', clickable: false },
    { header: '상태', accessor: 'status', clickable: false },
    { header: '가상 머신', accessor: 'vmCount', clickable: false },
    { header: '메모리', accessor: 'memoryUsage', clickable: false },
    { header: 'CPU', accessor: 'cpuUsage', clickable: false },
    { header: '네트워크', accessor: 'networkUsage', clickable: false },
    { header: 'SPM', accessor: 'spm', clickable: false },
  ],
  HOSTS_FROM_CLUSTER: [
    { header: '', accessor: 'icon', clickable: false },  // 이모티콘 칸
    { header: '이름', accessor: 'name', clickable: false },
    { header: '호스트이름/IP', accessor: 'hostNameIP', clickable: false },
    { header: '상태', accessor: 'status', clickable: false },
    { header: '불러오기', accessor: 'loading', clickable: false },
    { header: '디스플레이 주소 덮어쓰기', accessor: 'displayAddress', clickable: false }
  ],
  VMS: [
    { header: '', accessor: 'icon', clickable: false, style: { textAlign: 'center' } },
    { header: '이름', accessor: 'name', clickable: false },
    { header: '클러스터', accessor: 'cluster', clickable: false },
    { header: 'IP 주소', accessor: 'ipAddress', clickable: false },
    { header: 'vNIC 상태', accessor: 'vnicStatus', clickable: false },
    { header: 'vNIC', accessor: 'vnic', clickable: false },
    { header: 'vNIC Rx', accessor: 'vnicRx', clickable: false },
    { header: 'vNIC Tx', accessor: 'vnicTx', clickable: false },
    { header: '총 Rx', accessor: 'totalRx', clickable: false },
    { header: '총 Tx', accessor: 'totalTx', clickable: false },
    { header: '설명', accessor: 'description', clickable: false }
  ],
  VMS_FROM_HOST: [
    { header: '이름', accessor: 'name', clickable: false },
    { header: '클러스터', accessor: 'cluster', clickable: false },
    { header: 'IP 주소', accessor: 'ipAddress', clickable: false },
    { header: 'FQDN', accessor: 'fqdn', clickable: false },
    { header: '메모리', accessor: 'memory', clickable: false },
    { header: 'CPU', accessor: 'cpu', clickable: false },
    { header: '네트워크', accessor: 'network', clickable: false },
    { header: '상태', accessor: 'status', clickable: false },
    { header: '업타임', accessor: 'uptime', clickable: false },
  ],
  VMS_FROM_DISK: [
    { header: '이름', accessor: 'name', clickable: false },
    { header: '클러스터', accessor: 'cluster', clickable: false },
    { header: 'IP 주소', accessor: 'ipAddress', clickable: false },
    { header: 'FQDN', accessor: 'fqdn', clickable: false },
    { header: '메모리', accessor: 'memory', clickable: false },
    { header: 'CPU', accessor: 'cpu', clickable: false },
    { header: '네트워크', accessor: 'network', clickable: false },
    { header: '상태', accessor: 'status', clickable: false },
    { header: '업타임', accessor: 'uptime', clickable: false },
  ],
  TEMPLATES: [
    { header: '이름', accessor: 'name', clickable: false },
    { header: '버전', accessor: 'version', clickable: false },
    { header: '상태', accessor: 'status', clickable: false },
    { header: '클러스터', accessor: 'cluster', clickable: false },
    { header: 'vNIC', accessor: 'vnic', clickable: false },
  ],
  PERMISSIONS: [
    { header: '', accessor: 'icon', clickable: false },
    { header: '사용자', accessor: 'user', clickable: false },
    { header: '인증 공급자', accessor: 'authProvider', clickable: false },
    { header: '네임스페이스', accessor: 'namespace', clickable: false },
    { header: '역할', accessor: 'role', clickable: false },
    { header: '생성일', accessor: 'createdDate', clickable: false },
    { header: 'Inherited From', accessor: 'inheritedFrom', clickable: false },
  ],
  AFFINITY_LABELS: [
    { header: '이름', accessor: 'name', clickable: false },
    { header: '가상머신 멤버', accessor: 'vmMember', clickable: false },
    { header: '호스트 멤버', accessor: 'hostMember', clickable: false },
  ],
  SESSIONS: [
    { header: '세션 DB ID', accessor: 'sessionId', clickable: false },
    { header: '사용자 이름', accessor: 'username', clickable: false },
    { header: '인증 공급자', accessor: 'authProvider', clickable: false },
    { header: '사용자 ID', accessor: 'userId', clickable: false },
    { header: '소스 IP', accessor: 'sourceIp', clickable: false },
    { header: '세션 시작 시간', accessor: 'sessionStartTime', clickable: false },
    { header: '마지막 세션 활성', accessor: 'lastSessionActive', clickable: false },
  ],
  EVENTS: [
    { header: '', accessor: 'icon', clickable: false },
    { header: '시간', accessor: 'time', clickable: false },
    { header: '메세지', accessor: 'message', clickable: false },
    { header: '상관 관계 ID', accessor: 'correlationId', clickable: false },
    { header: '소스', accessor: 'source', clickable: false },
    { header: '사용자 지정 이벤트 ID', accessor: 'customEventId', clickable: false }
  ],
}

export default TableColumnsInfo