rootProject.name = "okestro-demo"
include(":monolith")
include(":common")
include(":util")
include(":util-ovirt")
include(":itcloud")
include(":license-common")
include(":license-enc")
include(":license-dec")
include(":license-validate")
