name: CI with Gradle

on: 
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout project's main branch
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run build with Gradle Wrapper
      run: ./gradlew monolith:war -Pprofile=staging
    
    - name: Upload to Github  
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: monolith/build/libs