name: Build and Publish itcloud Docker Image

on:
  push:
    tags:
      - 'itcloud-v*'  # Triggers on tags with prefix 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract version number
        id: extract_version
        run: |
          VERSION=$(echo "${GITHUB_REF}" | sed -E 's|refs/tags/itcloud-v(.*)|\1|')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Print extracted version
        run: |
          echo "Extracted version: ${{ env.VERSION }}"

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/itcloud:${{ env.VERSION }} --load .

      - name: Save Docker image as tarball
        run: |
          docker save ${{ secrets.DOCKER_HUB_USERNAME }}/itcloud:${{ env.VERSION }} -o itcloud-${{ env.VERSION }}.tar

      - name: Upload Docker image tarball as artifact
        uses: actions/upload-artifact@v3
        with:
          name: itcloud-${{ env.VERSION }}-tarball
          path: itcloud-${{ env.VERSION }}.tar
              
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/itcloud:${{ env.VERSION }}