name: Upload Artifact to Synology NAS

on:
  push:
    tags:
      - 'upload-v*'  # Triggers on tags with prefix 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Make test file
      run: echo "${{ github.sha }}" > test.txt
      
    - name: Debug Connection
      run: |
        echo "Testing connection to Synology NAS..."
        curl -v -k https://${{ secrets.SYNOLOGY_HOST }}:5001
        
    - name: Test upload
      uses: bungabear/synology_upload_action@master
      with:
        host: ${{ secrets.SYNOLOGY_HOST }}
        username:  ${{ secrets.SYNOLOGY_USERNAME }}
        password:  ${{ secrets.SYNOLOGY_PASSWORD }}
        filepath: test.txt
        filename:  synology_upload_test.txt
        uploadpath: /Source
        overwrite: true
        createparent: true