name: Test OVPN Connection

on:
  push:
    tags:
      - 'itcloud-v*'  # Triggers on tags with prefix 'v'


jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show github context object
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
  
  test:
    runs-on: ubuntu-latest
    name: Typical Usage of OpenVPN
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up OpenVPN
        run: |
          echo "${{ secrets.OVPN_CONFIG }}" > client.ovpn
          echo "${{ secrets.OVPN_PASS }}" > pass.txt
          sudo apt-get update
          sudo apt-get install -y openvpn openvpn-systemd-resolved
          sleep 30

      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: .github/workflows/client.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "hello world"
